import tkinter
root = tkinter.Tk()
def show():
    print("hello ashwini sir")
root.title("Rishabh Ishan Tkfile")
#root.geometry("500x500")
root.minsize(200,200)
root.maxsize(600,600)
root.configure(bg="green")
b=tkinter.Button(root,text="add",height=5,width=8,bd=10,bg="blue",activebackground="green",command=sum)
#b.grid(row=0,column=0)
#b1=tkinter.Button(root,text="sad",height=32,width=40,bd=10,bg="green",activebackground="blue")
#b1.grid(row=1,column=1)
b.place(x=100,y=130)
V=tkinter.StringVar()
V1=tkinter.StringVar()
V2=tkinter.StringVar()
def sum():
    a=int(V.get())
    b=int(V1.get())
    c=a+b
    V2.set(c)
L=tkinter.Label(root,text="First Number")
L.place(x=5,y=10)
e=tkinter.Entry(root,textvariable=V)
e.place(x=100,y=10)
L1=tkinter.Label(root,text="Second Number")
L1.place(x=5,y=50)
e1=tkinter.Entry(root,textvariable=V1)
e1.place(x=100,y=50)
L2=tkinter.Label(root,text="Result")
L2.place(x=5,y=90)
e2=tkinter.Entry(root,textvariable=V2)
e2.place(x=100,y=90)
#b.pack(side="left") 
root.mainloop()
